name: Bug Report / Suggestion
description: Report an issue or suggest improvements to the list
title: "[Issue] "
labels: ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or suggestion
    validations:
      required: true
